apiVersion: v1
kind: Secret
metadata:
  name: minio-access-keys
  namespace: data
type: Opaque
stringData:
  username: randomstring
  password: anotherrandomstring
---
apiVersion: minio.rook.io/v1alpha1
kind: ObjectStore
metadata:
  name: minio
  namespace: data
spec:
  scope:
    nodeCount: 4
    volumeClaimTemplates:
      - metadata:
          name: minio
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "rook-ceph-block"
          resources:
            requests:
              storage: "10Gi"
  credentials:
    name: minio-access-keys
    namespace: data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: data
spec:
  type: ClusterIP
  selector:
    app: minio
    objectstore: minio
  ports:
    - name: http-minio
      port: 9000
      targetPort: 9000
      protocol: TCP
