apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-member
  namespace: data
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","patch","watch"]
  - apiGroups: ["cassandra.rook.io"]
    resources: ["clusters"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-member
  namespace: data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cassandra-member
  namespace: data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cassandra-member
subjects:
  - kind: ServiceAccount
    name: cassandra-member
    namespace: data
