version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
    ports:
      - "3306:3306"
  hive-metastore:
    container_name: hive
    image: apk8s-hive-s3m:3.1.2
    environment:
      MYSQL_ENDPOINT: "mysql:3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "demo"
      S3A_ENDPOINT: "https://obj.data.dev5.apk8s.dev"
      S3A_ACCESS_KEY: "miniouser"
      S3A_SECRET_KEY: "miniopassword"
      S3A_PATH_STYLE_ACCESS: "true"
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - mysql
