apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: data
type: Opaque
stringData:
  ROOT_PASSWORD: strongpassword
  USER: hive
  PASSWORD: strongpassword
  DATABASE: objectmetastore
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql
  namespace: data
spec:
  replicas: 2
  secretName: mysql-credentials
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 1Gi
