apiVersion: v1
kind: ConfigMap
metadata:
  name: eth-geth
  namespace: data
  labels:
    app: eth-geth
data:
  networkid: "27587"
  genesis.json: |-
    {
        "config": {
            "chainId": 27587,
            "homesteadBlock": 0,
            "eip150Block": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "difficulty": "0x400",
        "gasLimit": "0x8000000",
        "nonce"   : "0x0000000000000000",
        "alloc": {
          "0xFa4087D3688a289c9C92e773a7b46cb9CCf80353": { "balance": "100000000000000000000" },
          "0x8ab8F3fc6c660d3f0B22490050C843cafd2c0AAC": { "balance": "200000000000000000000" }
        }
    }
